
export const rizeData = [
    { name: "Arnena Elek.Müzik Alt.San.İnş.Tur.Ltd.Şti.", area: 28.75, rate: 280, manager: "İrfan ÇALIK / Barış KÖSE", phone: "0 537 673 21 35", email: "irfancalik@hotmail.com.tr", floor: "Zemin" },
    { name: "Ali Gürbüz", area: 28.75, rate: 280, manager: "Ali GÜRBÜZ", phone: "0 532 492 95 09", email: "k.aligurbuz@gmail.com", floor: "Zemin" },
    { name: "İnce Ar-Ge Elek.Araştırma Geliştirme Ltd.Şti.", area: 5, rate: 350, manager: "Berkan Emre İNCE", phone: "0 531 287 69 39", email: "emreberkanince@gmail.com", floor: "Zemin" },
    { name: "Keveras Biyomedikal San.Tic. Ltd. Şti.", area: 15, rate: 0, manager: "Mehmet Sabri Balık", phone: "-", email: "sabri.balik@erdogan.edu.tr", floor: "Zemin" },
    { name: "ARBASOP ÇEVRE ARGE EĞT.DAN. PEYZAJ SAN. TİCARET LTD.ŞTİ.", area: 30, rate: 0, manager: "Bülent Verep", phone: "0 (533) 453 68 42", email: "verepoglu@hotmail.com", floor: "Zemin" },
    { name: "Rise Teknoloji", area: 35, rate: 0, manager: "-", phone: "-", email: "-", floor: "Zemin" },
    { name: "Alaaddin Yüksel-Bintek İleri Mühendislik ve Ormancılık", area: 30, rate: 0, manager: "Prof. Dr. Alaaddin Yüksel", phone: "(0532) 635 27 01", email: "ayuksel12@gmail.com", floor: "Zemin" },
    { name: "Coruh Ar-Ge ve Teknoloji San.Tic.Ltd.Şti.", area: 10, rate: 0, manager: "Uğur CORUH", phone: "0 537 513 20 13", email: "ugur.coruh.tr@gmail.com", floor: "Zemin" },
    { name: "Zeynep Yanbay Bakırcı Eynis Teknoloji", area: 10, rate: 175, manager: "Burak Bakırcı", phone: "-", email: "burakbakirci@gmail.com", floor: "Zemin" },
    { name: "Recep Tayyip Erdoğan Üniversitesi Tıp Fakültesi Histoloji ve Embriyoloji", area: 5, rate: 0, manager: "-", phone: "-", email: "-", floor: "Zemin" },
    { name: "Fish-Pro-Jel", area: 15, rate: 0, manager: "Dr. Ayşe Demirbaş", phone: "(536) 051-17-09", email: "ayse.demirbas@erdogan.edu.tr", floor: "Zemin" },
    { name: "İsa Çelik LABSCALER Araştırma ve Danışmanlık", area: 15, rate: 0, manager: "İsa Çelik", phone: "(507) 482-74-25", email: "isa.celik@erdogan.edu.tr", floor: "Zemin" },
    { name: "Agro-Tea", area: 20, rate: 0, manager: "Keziban Yazıcı", phone: "(505) 416-88-83", email: "keziban.yazici@erdogan.edu.tr", floor: "Zemin" },
    { name: "Plasmafor Tarım", area: 10, rate: 350, manager: "-", phone: "-", email: "-", floor: "Zemin" },
    { name: "Emarti Elektrik-Elektronik Tasarım, Yazılım, Ar-Ge, Danışmanlık Ltd.Şti", area: 20, rate: 0, manager: "-", phone: "-", email: "-", floor: "Zemin" },
    { name: "Zugaps", area: 10, rate: 0, manager: "Yunus Karabulut", phone: "(554) 120-35-52", email: "-", floor: "Zemin" },
    { name: "Luzeri LTD", area: 15, rate: 0, manager: "-", phone: "-", email: "-", floor: "Zemin" },
    { name: "Soluvione", area: 15, rate: 0, manager: "Berk Er", phone: "-", email: "ber@soluvione.com", floor: "Zemin" },
    { name: "Murat Hacımurtaroğlu", area: 20, rate: 0, manager: "Murat Hacımurtazoğlu", phone: "-", email: "murat.hacimurtazaoglu@erdogan.edu.tr", floor: "Zemin" },
    { name: "Karageyik Yazılım Ve Bilişim San. Tic. Ltd. Şti.", area: 10, rate: 0, manager: "Ferhat Özçelik", phone: "(543) 257-91-35", email: "fersat@hizirpaket.com", floor: "Zemin" },
    { name: "Renewasoft Enerji ve Yazılım A.Ş.", area: 5, rate: 0, manager: "Mehmet Sevri", phone: "-", email: "mehmetsevri@gmail.com", floor: "Zemin" },
    { name: "MAGarden Tarım Ltd. Şti.", area: 5, rate: 0, manager: "Mustafa Akbulut", phone: "-", email: "makbuluttr@gmail.com", floor: "Zemin" },
    { name: "Sinatr Teknoloji Ltd.Şti.", area: 10, rate: 0, manager: "-", phone: "-", email: "-", floor: "Zemin" },
    { name: "GeoMED Coğrafi Bilişim Teknolojileri ve Dijital Sağlık San.Tic. Ltd.Şti", area: 25, rate: 0, manager: "Doç. Dr. Neslihan Özçelik", phone: "-", email: "geomed@geomed.com.tr", floor: "Zemin" }
];

export const atasehirData = [
    { name: "T-Tech Business Solutions Yaz.Dan.Hiz.Tic. A.Ş.", floor: "25", area: 157, rate: 2250, manager: "TİMUR KAHRAMAN", phone: "(538) 862-69-66", email: "timur.karaman@tiryaki.com.tr", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "YÖNETİM", floor: "24", area: 763 },
    { name: "Siemens Sanayi ve Ticaret A.Ş.", floor: "23A", area: 763, rate: 2163, manager: "Berna Sural", phone: "(531) 101-66-08", email: "berna.sural@siemens.com", sector: "Yarı İletken ve Elektronik Donanım" },
    { name: "Odifin Stratejik Dan.Hiz.A.Ş.", floor: "23", area: 127.4, rate: 2250, manager: "Emine Akman", phone: "535 437 22 02", email: "emine.akman@odifin.com", sector: "Veri Analitiği ve Yönetimi" },
    { name: "Qco Quantum Computıng Teknoloji A.Ş.", floor: "23", area: 53.6, rate: 2250, manager: "Abdurahman Keklik", phone: "(533) 744-22-20", email: "mustafa.oztas@compro.com.tr", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "F8 BİLİŞİM VE DANIŞMANLIK HİZMETLERİ LTD. ŞTİ.", floor: "23", area: 142, rate: 2250, manager: "Faruk Azaklı", phone: "(533) 596-09-88", email: "faruk.azakli@f8.com.tr", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Gentek Elektronik San. Tic. A.Ş", floor: "23", area: 76, rate: 2250, manager: "Atakan Aydın", phone: "(538) 329-47-55", email: "a.aydin@gentekelektronik.com.tr", sector: "Yarı İletken ve Elektronik Donanım" },
    { name: "Aritatürk Bilişim Ve Dan.Hiz.San.Ve Tic. A.Ş.", floor: "23", area: 75, rate: 2061, manager: "Bahadır Babalı", phone: "(541) 486-31-86", email: "bahadir.babali@aritaturk.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Eşarj Elektrikli Araçlar Şarj Sistemleri A.Ş", floor: "23", area: 63, rate: 2250, manager: "Sevil BEYENİRSOY", phone: "(542) 349-40-10", email: "sevil.beyenirsoy@esarj.com", sector: "Makine ve Endüstriyel Otomasyon" },
    { name: "Net Koruma Marka ve Siber Güvenlik Dan. Hiz. Ltd.Şti.", floor: "23", area: 62, rate: 2250, manager: "Salih BULUT", phone: "(532) 293-77-90", email: "salih.bulut@netkoruma.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "BS Sistem Teknolojileri Anonim Şirketi", floor: "23", area: 52, rate: 2250, manager: "Mutlu Yılmaz", phone: "(530) 517-75-01", email: "myilmaz5914@gmail.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Sqılls Turkey Bilgi Teknolojileri Tic.Ltd.Şti.", floor: "22A", area: 350, rate: 2250, manager: "Mustafa İncel", phone: "(532) 490-35-32", email: "mustafa.incel@sqills.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Nika Teknoloji Anonim Şirketi", floor: "22A", area: 165, rate: 2250, manager: "Kazım Erdur", phone: "(530) 613-82-13", email: "muhasebe@nikateknoloji.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Novafinz Finansal Dönüşüm Teknolojileri A.Ş.", floor: "22A", area: 150, rate: 2250, manager: "Adem Aydın", phone: "(538) 810-67-56", email: "adem.aydin@pionr.ventures", sector: "Finansal Teknolojiler (Fintech)" },
    { name: "Sardeks Teknoloji Anonim Şirketi", floor: "22A", area: 98, rate: 2250, manager: "MURAT GÜZEL", phone: "0549 234 34 35", email: "murat.guzel@sardeks.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Misyon Finansal Teknoloji A.Ş.", floor: "22", area: 389, rate: 1957, manager: "Mert Wang", phone: "(532) 111-22-33", email: "mertwang@misyontech.com", sector: "Finansal Teknolojiler (Fintech)" },
    { name: "Turkchip Teknoloji San.ve Tic.A.Ş.", floor: "21", area: 546, rate: 1854, manager: "Uğur CORUH", phone: "(533) 999-88-77", email: "ugur.coruh.tr@gmail.com", sector: "Yarı İletken ve Elektronik Donanım" },
    { name: "Bhl Turkey Teknoloji Anonim Şirketi", floor: "21", area: 217, rate: 2250, manager: "Erdoğan Can DİLEK", phone: "(542) 555-44-33", email: "erdogancan.dilek@hesapkurdu.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Siemens Sanayi ve Ticaret A.Ş.", floor: "20", area: 763, rate: 2163, manager: "Berna Sural", phone: "(531) 101-66-08", email: "berna.sural@siemens.com", sector: "Yarı İletken ve Elektronik Donanım" },
    { name: "Onbt Bilişim Teknolojileri A.Ş.", floor: "19", area: 440, rate: 2250, manager: "Oğuzhan Yıldız", phone: "(535) 222-33-44", email: "oguzhan.yildiz@onbt.com.tr", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Pinsoft Bilişim Teknolojileri ve Dan.Tic. Ltd. Şti.", floor: "19", area: 322, rate: 1751, manager: "Ahmet Erkam Mete", phone: "(532) 444-55-66", email: "ahmet.mete@pinsoft.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Universal Yazılım Anonim Şirketi", floor: "18", area: 464, rate: 1544, manager: "Osman SÖNMEZ", phone: "(533) 777-88-99", email: "osman.sonmez@universal.com.tr", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Remap Teknoloji Çözümleri A.Ş.", floor: "18", area: 143, rate: 1544, manager: "Kaan GÜRLER", phone: "(544) 666-55-44", email: "kaan.gurler@remap.com.tr", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "BOŞ-DKM REZERVE", floor: "18", area: 99 },
    { name: "Viasu Teknoloji A.Ş.", floor: "18", area: 22, rate: 1544, manager: "Gökhan CİVELEK", phone: "(532) 123-45-67", email: "gokhan.civelek@viasu.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Pozitftech Bilişim Teknolojileri A.Ş.", floor: "17", area: 336, rate: 1957, manager: "Mustafa Kalkanlı", phone: "(532) 987-65-43", email: "mustafa.kalkanli@pozitftech.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Nu Teknoloji A.Ş.", floor: "17", area: 213.5, rate: 2000, manager: "Ali Yasin ERDOĞAN", phone: "(533) 321-65-49", email: "ali.erdogan@nuteknoloji.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Nu Teknoloji A.Ş.", floor: "17", area: 213.5, rate: 2000, manager: "Ali Yasin ERDOĞAN", phone: "(533) 321-65-49", email: "ali.erdogan@nuteknoloji.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Odea Teknoloji Hizmetleri A.Ş.", floor: "16", area: 763, rate: 1957, manager: "Fevzi BÜYÜKMIGIRDIC", phone: "(532) 456-78-90", email: "fevzi.bm@odeatech.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Siemens Sanayi ve Ticaret A.Ş.", floor: "14", area: 763, rate: 2163, manager: "Berna Sural", phone: "(531) 101-66-08", email: "berna.sural@siemens.com", sector: "Yarı İletken ve Elektronik Donanım" },
    { name: "Deloitte", floor: "13", area: 763, rate: 1957, manager: "Yetkili", phone: "(212) 366-60-00", email: "info@deloitte.com.tr", sector: "Veri Analitiği ve Yönetimi" },
    { name: "UPT TECH TEKNOLOJİ A.Ş.", floor: "12", area: 300, rate: 1700, manager: "HAKAN UZUN", phone: "(532) 211-33-44", email: "hakan.uzun@upt.com.tr", sector: "Finansal Teknolojiler (Fintech)" },
    { name: "Icredıble Yazılım Teknoloji A.Ş.", floor: "12", area: 224, rate: 2250, manager: "Mustafa COŞKUN", phone: "(533) 888-99-00", email: "mustafa.coskun@icredible.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Digitallency Bilişim Hizmetleri Ticaret A.Ş.", floor: "11", area: 287, rate: 1544, manager: "Uraz Yekta İŞERİ", phone: "(542) 777-66-55", email: "uraz.iseri@digitallency.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Damalink Bilişim Dan. ve Ticaret A.Ş", floor: "11", area: 218, rate: 1544, manager: "Miraç Eminağaoğlu", phone: "(532) 555-11-22", email: "mirac.eminagaoglu@damalink.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Bi Stratejik Yazılım San.Tic.A.Ş.", floor: "11", area: 125, rate: 1544, manager: "İbrahim KOCASARI", phone: "(533) 444-33-22", email: "ibrahim.kocasari@bistratejik.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "KOMTAŞ BİLGİ YÖNETİMİ DANIŞMANLIK A.Ş", floor: "11", area: 98, rate: 1544, manager: "Yüksel Çomak", phone: "(535) 666-77-88", email: "yuksel.comak@komtas.com", sector: "Veri Analitiği ve Yönetimi" },
    { name: "DFL Teknoloji A.Ş.", floor: "11", area: 35, rate: 1544, manager: "Deniz Şerbetçioğlu", phone: "(532) 999-00-11", email: "deniz.serbetcioglu@dfl.com.tr", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Valde Bilişim Teknolojileri Ticaret A.Ş.", floor: "10", area: 264, rate: 2250, manager: "Azmi ALEMDAR", phone: "(533) 123-98-76", email: "azmi.alemdar@valde.com.tr", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Dzd Teknoloji Sanayi ve Tic.Ltd.Şti.", floor: "10", area: 214, rate: 1699, manager: "Ziya ÇALIK", phone: "(542) 321-67-89", email: "ziya.calik@dzd.com.tr", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Dgpaysıt Bilişim Teknolojileri A.Ş.", floor: "9", area: 763, rate: 1802, manager: "Hasan KAYA", phone: "(532) 444-99-88", email: "hasan.kaya@dgpays.com", sector: "Finansal Teknolojiler (Fintech)" },
    { name: "AGİTO BİLGİSAYAR YAZILIM VE DANIŞMANLIK A.Ş.", floor: "8", area: 763, rate: 1544, manager: "Selen Engür Özkırım", phone: "(212) 333-22-11", email: "selen.engur@agito.com.tr", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Odea Teknoloji Hizmetleri A.Ş.", floor: "7", area: 763, rate: 1957, manager: "Fevzi BÜYÜKMIGIRDIC", phone: "(532) 456-78-90", email: "fevzi.bm@odeatech.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Amaris Teknoloji İstanbul Dan.Ltd.Şti.", floor: "6", area: 241, rate: 2250, manager: "Özgün Hande Ökülke", phone: "(533) 222-11-00", email: "hande.okulke@amaris.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Carbon Dan. ve Bilgi Teknolojileri A.Ş.", floor: "6", area: 210, rate: 1648, manager: "Serkan Kızıler", phone: "(532) 777-88-99", email: "serkan.kiziler@carbon.com.tr", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Beyond Guard Yazılım Ve Danışmanlık", floor: "6", area: 70, rate: 1648, manager: "Süleyman ÖZARSLAN", phone: "(542) 555-66-77", email: "suleyman.ozarslan@beyondguard.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Biart Bilişim Teknolojileri Ltd. Şti.", floor: "4", area: 185, rate: 1544, manager: "Artun Cumhur", phone: "(535) 999-88-77", email: "artun.cumhur@biart.com.tr", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "NG YAZILIM VE DANIŞMANLIK LİMİTED ŞİRKETİ", floor: "4", area: 98, rate: 1648, manager: "Nevzat GÜNERİ", phone: "(532) 111-22-99", email: "nevzat.guneri@ngyazilim.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "FİNALCHECK TEKNOLOJİ VE YÖNETİM SİSTEMLERİ", floor: "4", area: 84, rate: 1544, manager: "Salih Çelikli", phone: "(533) 333-44-55", email: "salih.celikli@finalcheck.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Mimeda Medya Platform Anonim Şirketi", floor: "4", area: 75, rate: 2250, manager: "Kaan Çetinkaya", phone: "(542) 666-55-44", email: "kaan.cetinkaya@mimeda.com", sector: "Medya ve Dijital Pazarlama" },
    { name: "My Analytics Bilişim Sis. ve Hiz. Tic.A.Ş.", floor: "4", area: 42, rate: 1544, manager: "Emre ÇATAK", phone: "(532) 888-77-66", email: "emre.catak@myanalytics.com", sector: "Veri Analitiği ve Yönetimi" },
    { name: "Dgpaysıt Bilişim Teknolojileri A.Ş.", floor: "3", area: 381.5, rate: 1802, manager: "Hasan KAYA", phone: "(532) 444-99-88", email: "hasan.kaya@dgpays.com", sector: "Finansal Teknolojiler (Fintech)" },
    { name: "Unico Sigorta A.Ş.", floor: "3", area: 381.5, rate: 2250, manager: "SERTAÇ NAİLİ", phone: "(212) 222-33-44", email: "sertac.naili@unicosigorta.com.tr", sector: "Finansal Teknolojiler (Fintech)" },
    { name: "Fair Teknoloji A.Ş.", floor: "2A", area: 763, rate: 2061, manager: "İLKER İŞLİER", phone: "(533) 555-44-33", email: "ilker.islier@fairteknoloji.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "RDC Partner Bil.an. ve Teknoloji Hiz A.Ş.", floor: "2", area: 316, rate: 1648, manager: "HÜSEYİN YORGANCİ", phone: "(532) 999-11-22", email: "huseyin.yorganci@rdcpartner.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Pentanom Teknoloji A.Ş.", floor: "2", area: 200, rate: 2250, manager: "Mevlüt Şahin", phone: "(542) 777-88-99", email: "mevlut.sahin@pentanom.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "Payosfer Bilişim Hizmetleri Anonim Şirketi", floor: "2", area: 90, rate: 1442, manager: "Yalçın AYDİN", phone: "(535) 333-22-11", email: "yalcin.aydin@payosfer.com", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "YÖNETİM", floor: "1A", area: 190 },
    { name: "ETKİN PROJE YÖNETİM DANIŞMANLIK TİC LTD ŞTİ", floor: "1", area: 216, rate: 1050, manager: "İbrahim BODUR", phone: "(532) 123-32-10", email: "ibrahim.bodur@etkinproje.com", sector: "Veri Analitiği ve Yönetimi" },
    { name: "YÖNETİM", floor: "1", area: 141 },
    { name: "P Tech Solutions Teknoloji Ve Bilişim Hiz.A.Ş.", floor: "Zemin Asma", area: 553, rate: 2061, manager: "Zeynep BİLAL", phone: "(533) 987-12-34", email: "zeynep.bilal@ptech.com.tr", sector: "Yazılım ve Bilişim Hizmetleri" },
    { name: "YEMEKHANE", floor: "-1", area: 2300 }
];

export const atasehirCommonAreaData = [
    { "name": "Enderun Bilişim Sanayi Ve Dış Ticaret Limited Şirketi", "floor": "Zemin", "area": 5, "rate": 8915, "manager": "Salim Gören", "phone": "(554) 429-08-08", "email": "salim.goren@enderunstudios.com" },
    { "name": "Kontra Siber Savunma Teknoloji Limited Şirketi", "floor": "Zemin", "area": 2, "rate": 9906, "manager": "Yavuz Atlas", "phone": "(536) 685-21-64", "email": "yavuzatlas@gmail.com" },
    { "name": "Bexfa Teknoloji A.Ş.", "floor": "Zemin", "area": 7, "rate": 10500, "manager": "Ahmet Kamil", "phone": "(551) 019-36-46", "email": "ahmet.kamil@bexfa.com" },
    { "name": "Qberx Teknoloji A.Ş.", "floor": "Zemin", "area": 2, "rate": 9906, "manager": "Aslı Berrak Yenal", "phone": "(530) 784-83-38", "email": "berrak.yenal@gmail.com" },
    { "name": "AYRO Teknoloji Yazılım Dan. ve Eğitim Tic. Ltd. Şti.", "floor": "Zemin", "area": 1, "rate": 10500, "manager": "Ülker Gürpınar", "phone": "(546) 780-43-70", "email": "ulker.gurpinar@ayrotek.com.tr" },
    { "name": "Masterkey Dijital Teknoloji Anonim Şirketi", "floor": "Zemin", "area": 3, "rate": 9906, "manager": "Bünyamin Yılmaz", "phone": "(533) 209-12-53", "email": "bunyamin.yilmaz@masterkey.com.tr" },
    { "name": "Masterkey Dijital Teknoloji Anonim Şirketi", "floor": "Zemin", "area": 4, "rate": 12500, "manager": "Bünyamin Yılmaz", "phone": "(533) 209-12-53", "email": "bunyamin.yilmaz@masterkey.com.tr" },
    { "name": "Forcerta Bilgi Teknolojileri A.Ş.", "floor": "Zemin", "area": 3, "rate": 10500, "manager": "Melih Büyükbayram", "phone": "(530) 155-11-20", "email": "melih.buyukbayram@fincraft.com.tr" },
    { "name": "Alte Teknoloji Eğitim Ve Danışmanlık Hizm. Ltd.Şti.", "floor": "Zemin", "area": 4, "rate": 9906, "manager": "Bekir İnce", "phone": "(543) 352-52-00", "email": "bince@sakarya.edu.tr" },
    { "name": "Oxeras Danışmanlık Ltd.Şti.", "floor": "Zemin", "area": 2, "rate": 10500, "manager": "Ozan Eroğlu", "phone": "0532 781 81 18", "email": "ozan.eroglu@oxeras.com" },
    { "name": "Pupas Teknoloji Yatırımları Dan. A.Ş.", "floor": "Zemin", "area": 1, "rate": 9906, "manager": "Ayhan Aydoğan", "phone": "(539) 383-76-12", "email": "ayhan@pupas.co" },
    { "name": "Çözümtek Bilgi Teknolojileri A.Ş.", "floor": "Zemin", "area": 4, "rate": 10500, "manager": "Engin Çetinkaya", "phone": "5323339954", "email": "engin@cozumtek.com" },
    { "name": "Connect Dijital Hizmetler A.Ş.", "floor": "Zemin", "area": 10, "rate": 10500, "manager": "Semih Açıkgöz", "phone": "(533) 607-36-55", "email": "groupmturkiye.marketing@groupm.com" },
    { "name": "Nerodata Teknoloji Anonim Şirketi", "floor": "Zemin", "area": 1, "rate": 10500, "manager": "Hasan Can Saral", "phone": "(533) 521-36-28", "email": "hasan.saral@nerodata.com" },
    { "name": "Paymago Finansal Teknoloji Hiz. A.Ş.", "floor": "Zemin", "area": 5, "rate": 9906, "manager": "Derviş Ahmet Aydın", "phone": "5368372232", "email": "dervisaydin@paymago.com" },
    { "name": "Ideas Müh.Ve Tasarım Hiz.Tic.A.Ş.", "floor": "Zemin", "area": 11, "rate": 9906, "manager": "Jakson Cenk Mübarek", "phone": "(542) 301-10-01", "email": "cenkmubarek@darhan.com.tr" },
    { "name": "UnoPro Üretim ve Danışmanlık San. ve Tic. Ltd. Şti.", "floor": "Zemin", "area": 1, "rate": 9906, "manager": "Doğan Hasan", "phone": "(551) 021-37-27", "email": "dogan.hasan@unopro.com.tr" },
    { "name": "Be Green Coaching Spor Danışmanlığı LTD.ŞTİ.", "floor": "Zemin", "area": 1, "rate": 10500, "manager": "Mustafa Yıldız", "phone": "(531) 389-50-10", "email": "mustafayildizfit@gmail.com" },
    { "name": "Intranet Technology Yazılım Anonim Şirketi", "floor": "Zemin", "area": 9, "rate": 9906, "manager": "Enes Tütüncü", "phone": "(531) 987-20-51", "email": "enes@paywall.one" },
    { "name": "Upagon Teknoloji Ve Danışmanlık Anonim Şirketi", "floor": "Zemin", "area": 1, "rate": 10500, "manager": "Erdinç Sezer", "phone": "(532) 524-05-71", "email": "erdinc.sezer@upagon.com" },
    { "name": "Getclinic Sağlık Ve Bilgi Teknolojileri Anonim Şirketi", "floor": "Zemin", "area": 1, "rate": 10500, "manager": "Berk Topçu", "phone": "(533) 077-35-54", "email": "berk@getclinic.com" },
    { "name": "Teknotel Elektronik Mühendislik San.Ve Tic.Ltd. Şti.", "floor": "Zemin", "area": 2, "rate": 10500, "manager": "Mesut Kartal", "phone": "0555 711 95 57", "email": "emre.kurt@teknotel.com.tr" },
    { "name": "Aims Yapay Zeka Ve Yönetim Çözümleri A.Ş.", "floor": "Zemin", "area": 5, "rate": 9906, "manager": "Tulin Güzel", "phone": "(541) 312-08-94", "email": "tguzel@aims.com.tr" },
    { "name": "EBK Yazılım Limited Şirketi", "floor": "Zemin", "area": 1, "rate": 10500, "manager": "Hakan Süleyman Küçük", "phone": "(533) 325-04-63", "email": "hakanskucuk@gmail.com" },
    { "name": "Minus99 Teknoloji A.Ş.", "floor": "Zemin", "area": 2, "rate": 8915, "manager": "Alaa Alnuaimi", "phone": "(530) 975-25-66", "email": "alaa@minus99.com" },
    { "name": "Orbislabs AI Teknoloji Anonim Şirketi", "floor": "Zemin", "area": 6, "rate": 10500, "manager": "Nesip İlker Altıntaş", "phone": "(554) 367-54-83", "email": "ilker.altintas@komtas.com" },
    { "name": "Pollyfy Yazılım Danışmanlık Ve Araştırma Tic.Ltd.Şti", "floor": "Zemin", "area": 1, "rate": 10500, "manager": "Murat Akşit", "phone": "0539 778 04 46", "email": "murat@bigcatresearch.com" },
    { "name": "Voxtechs Bilişim Teknolojileri A.Ş.", "floor": "Zemin", "area": 5, "rate": 9906, "manager": "Okan Gündoğdu", "phone": "5423876550", "email": "okan.gundogdu@voxtechs.com" },
    { "name": "Üstad Teknoloji A.Ş.", "floor": "Zemin", "area": 3, "rate": 9906, "manager": "Alper Çaltekin", "phone": "(532) 665-68-68", "email": "alpercaltekin@gmail.com" },
    { "name": "Yalın Patent Arge Danışmanlık Limited Şirketi", "floor": "Zemin", "area": 1, "rate": 10500, "manager": "-", "phone": "-", "email": "-" },
    { "name": "Abit Danışmanlık Bilgisayar Ve Eğitim Hiz.Tic.Ltd.Şti", "floor": "Zemin", "area": 3, "rate": 9906, "manager": "Ergenç Avcı", "phone": "(533) 561-03-30", "email": "ergenc.avci@abit.com.tr" },
    { "name": "İntepo Turkey Teknoloji Limited", "floor": "Zemin", "area": 2, "rate": 10500, "manager": "Fatih Koray Yıldız", "phone": "0 532 292 99 20", "email": "koray.yildiz@intepo.com.tr" },
    { "name": "P Yazılım Ve Bilgi Teknolojileri Anonim Şirketi", "floor": "Zemin", "area": 5, "rate": 9906, "manager": "Murat Kader", "phone": "(537) 835-40-40", "email": "fatih.cakar@path.com.tr" },
    { "name": "Eşarj Elektrikli Araçlar Şarj Sistemleri A.Ş.", "floor": "Zemin", "area": 8, "rate": 10500, "manager": "Sevil Beyenirsoy", "phone": "(542) 349-40-10", "email": "sevil.beyenirsoy@esarj.com" },
    { "name": "Gentek Elektronik San. Tic. A.Ş", "floor": "Zemin", "area": 3, "rate": 10500, "manager": "Atakan Aydın", "phone": "(538) 329-47-55", "email": "a.aydin@gentekelektronik.com.tr" },
    { "name": "NG Yazılım ve Danışmanlık Ltd. Şti.", "floor": "Zemin", "area": 5, "rate": 10500, "manager": "Recep Eymen Günaydın", "phone": "(542) 561-27-16", "email": "eymen.gunaydin@ngss.io" },
    { "name": "Payosfer Bilişim Hizmetleri Anonim Şirketi", "floor": "Zemin", "area": 1, "rate": 10500, "manager": "Murat Keşke", "phone": "(506) 605-28-71", "email": "murat.keske@payosfer.com" },
    { "name": "EldaSoft Yazılım ve Dan. Ltd. Şti.", "floor": "Zemin", "area": 2, "rate": 9906, "manager": "Ertan Galiba", "phone": "(505) 750-27-85", "email": "ertan@eldasoft.com" },
    { "name": "Diyalog Bilişim Teknolojileri ve Atık Yönetim Sanayi Tic.A.Ş.", "floor": "Zemin", "area": 1, "rate": 10500, "manager": "Botan Kongül", "phone": "(537) 371-93-86", "email": "botankongul1@gmail.com" },
    { "name": "Pars Finans Teknoloji Anonim Şirketi", "floor": "Zemin", "area": 2, "rate": 10500, "manager": "Derviş Ahmet Aydın", "phone": "5368372232", "email": "dervisaydin@paymago.com" },
    { "name": "Techpoint Arge Ve Destek Hizmetleri Anonim Şirketi", "floor": "Zemin", "area": 1, "rate": 10500, "manager": "Hülya Veis", "phone": "0507 344 01 87", "email": "hulya.veis@techpo.net" },
    { "name": "Turuncu Profesyonel Bilgi Teknolojileri A.Ş.", "floor": "Zemin", "area": 1, "rate": 12500, "manager": "Bahadır Bakır", "phone": "(533) 416-37-70", "email": "bahadir@e-imzaburada.com" },
    { "name": "Uren Bilişim Teknoloji Sanayi ve Ticaret A.Ş.", "floor": "Zemin", "area": 1, "rate": 10500, "manager": "Cengiz Çalışkan", "phone": "(555) 719-45-90", "email": "cengizcaliskan@bebarbilim.net" },
    { "name": "Mobil Arge Bilgi Teknolojileri İletişim Hiz.Ltd.Şti.", "floor": "Zemin", "area": 1, "rate": 10500, "manager": "Azra Maden", "phone": "0 551 535 03 00", "email": "azra.maden@mobilarge.com.tr" },
    { "name": "Mobil Arge Bilgi Teknolojileri İletişim Hiz.Ltd.Şti.", "floor": "Zemin", "area": 34.7, "rate": 5850, "manager": "Azra Maden", "phone": "0 551 535 03 00", "email": "azra.maden@mobilarge.com.tr" },
    { "name": "Dna Proje Ve Yazılım Anonim Şirketi", "floor": "Zemin", "area": 47.7, "rate": 5850, "manager": "Aykut Haşim Özdoğan", "phone": "(544) 738-81-01", "email": "nur.cimen@dna.com.tr" },
    { "name": "Cubewise Bilişim Limited Şirketi", "floor": "Zemin", "area": 33.62, "rate": 5850, "manager": "Faik Ulaş Bozkurt", "phone": "(535) 978-82-27", "email": "ubozkurt@cubewise.com" },
    { "name": "Youthside Teknoloji Ve İnsan Kaynakları A.Ş.", "floor": "Zemin", "area": 15.9, "rate": 5850, "manager": "Olcay Aksoy", "phone": "(554) 925-86-05", "email": "olcay.aksoy@youthside.co" },
    { "name": "Novatech Global Mühendislik Ltd.Şti.", "floor": "Zemin", "area": 13.6, "rate": 5850, "manager": "Koray Kandemir", "phone": "0532 282 67 77", "email": "koray.kandemir@novatechglobal.com" },
    { "name": "Sisal Technology Yazılım A.Ş.", "floor": "Zemin", "area": 125.8, "rate": 5850, "manager": "Ozan Solmaz", "phone": "(530) 526-07-27", "email": "ozan.solmaz@fluttersea.com" },
    { "name": "Iconium Yazılım Ve Danışmanlık Hiz.Ltd.Şti.", "floor": "Zemin", "area": 45.3, "rate": 5850, "manager": "Hakan Uçan", "phone": "(532) 478-41-42", "email": "hakan.ucan@fit-global.com" },
    { "name": "Digital Cosmonot Bilişim Danışmanlık Eğitim Ltd. Şti", "floor": "Zemin", "area": 11.4, "rate": 5850, "manager": "Selim Çalık", "phone": "(543) 246-81-00", "email": "selim.calik@digitalcosmonot.com" },
    { "name": "DKM İnşaat ve Danışmanlık San. Tic. A.Ş.", "floor": "Zemin", "area": 31.8, "rate": 5850, "manager": "Volkan Dikmen", "phone": "(541) 459-30-91", "email": "volkandikmen@dkminsaat.com" },
    { "name": "Dornick Studios Teknoloji A.Ş.", "floor": "Zemin", "area": 27.1, "rate": 5850, "manager": "Alper Katırcı", "phone": "(539) 256-57-58", "email": "alper.katirci@aizonatech.com" },
    { "name": "Aydın Pelin- Can Binzet Müşavir Mühendislik A.Ş.", "floor": "Zemin", "area": 14, "rate": 5850, "manager": "-", "phone": "-", "email": "-" },
    { "name": "Consight Bilişim Teknolojileri Ve Mühendislik Anonim Şirketi", "floor": "Zemin", "area": 18.5, "rate": 5850, "manager": "Oğuzhan Yıldız", "phone": "(532) 690-62-08", "email": "oyildiz@kalyonholding.com" },
    { "name": "Minddx Dijital Dönüşüm Teknolojileri Sanayi Ve Ticaret A.Ş.", "floor": "Zemin", "area": 40.9, "rate": 5850, "manager": "Sümeyye Çiftçi", "phone": "(539) 255-05-44", "email": "arge@erpateknoloji.com" },
    { "name": "Dornick Studios Teknoloji A.Ş.", "floor": "Zemin", "area": 7, "rate": 10500, "manager": "Alper Katırcı", "phone": "(539) 256-57-58", "email": "alper.katirci@aizonatech.com" },
    { "name": "Pop Yazılım Ve Teknoloji Ürünleri Anonim Şirketi", "floor": "Zemin", "area": 3, "rate": 5850, "manager": "Abdülkadir Hacıoğlu", "phone": "0534 835 17 07", "email": "abdulkadir.hacioglu@gamelab.istanbul" }
];

export const cekmekoyOrtakAlanData = [
    { name: "Siyah Martı Medya A.Ş.", area: 3, rate: 6934, manager: "Kerem Tülün", phone: "(532) 346-32-77", email: "info@siyahmarti.com", floor: "Zemin" },
    { name: "Lobitek Yazılım A.Ş.", area: 3, rate: 6934, manager: "Yasin Çoban", phone: "(543) 582-41-95", email: "info@lobitek.com", floor: "Zemin" },
    { name: "Machinarium Teknoloji A.Ş.", area: 4, rate: 6934, manager: "Gökhan Uygun", phone: "0 506 854 20 21", email: "hr@machinarium.co", floor: "Zemin" },
    { name: "Depixen Yazılım ve Bilişim", area: 4, rate: 9500, manager: "Özgü Atalay", phone: "(505) 649-71-51", email: "oguz@mibosowellbeing.com", floor: "Zemin" },
    { name: "Customstech Bilgi Tek.", area: 4, rate: 9500, manager: "Oğuz Çekin", phone: "(539) 380-31-28", email: "info@customs.tech", floor: "Zemin" },
    { name: "Dijital Veri Yönetimi Ltd.", area: 11, rate: 9500, manager: "Murat Nurullahoglu", phone: "(531) 668-11-03", email: "murat.nurullahoglu@beinsights.net", floor: "Zemin" },
    { name: "Shıpnk Teknoloji A.Ş.", area: 2, rate: 9500, manager: "Oytun Yüksel", phone: "(555) 254-00-99", email: "info@shipink.io", floor: "Zemin" },
    { name: "Centro Teknoloji A.Ş.", area: 1, rate: 7925, manager: "Eray Arat", phone: "(542) 561-22-18", email: "eray.arat@centroservices.com", floor: "Zemin" },
    { name: "Kartis Teknoloji A.Ş.", area: 1, rate: 9500, manager: "Mehmed Eroğlu", phone: "0532 136 03 03", email: "eroglume@gmail.com", floor: "Zemin" },
    { name: "Talha Özay Uluğ Berrak Tek.", area: 2, rate: 9500, manager: "Talha Özay Uluğ", phone: "0 (532) 387-79-63", email: "ozay.ulug@alberen.com.tr", floor: "Zemin" },
    { name: "Bilgi Sistemleri San. Tic. A.Ş.", area: 1, rate: 9500, manager: "Bekir Sami Nalbantoğlu", phone: "0 (544) 190 41 34", email: "bekir.sami@bilgisistemleri.com.tr", floor: "Zemin" },
    { name: "Kaldera Mad. Mak. San.", area: 4, rate: 7925, manager: "Mustafa Koray Şahin", phone: "0532 661 6093", email: "info@kaldera.com.tr", floor: "Zemin" },
    { name: "Mengükan Yazılım Ltd.", area: 2, rate: 7925, manager: "Kurtuluş Mengükan", phone: "(537) 251-16-00", email: "info@mengukan.com", floor: "Zemin" },
    { name: "Tansa Güvenlik Sistemleri", area: 5, rate: 9500, manager: "Yalçın Sarı", phone: "(542) 585-49-00", email: "info@tansa.com.tr", floor: "Zemin" },
    { name: "Ths Finansal Tek. A.Ş.", area: 4, rate: 9500, manager: "Adem Aydın", phone: "(538) 810-67-56", email: "adem.aydin@pionr.ventures", floor: "Zemin" },
    { name: "Condolife Bilişim Tek.", area: 8, rate: 6934, manager: "Hezan Özbek", phone: "0 532 435 37 22", email: "hezan@altamira.com.tr", floor: "Zemin" },
    { name: "Finpro Danışmanlık Yazılım", area: 3, rate: 7925, manager: "İsmail Yakut", phone: "5335250444", email: "info@finpro.com.tr", floor: "Zemin" },
    { name: "Exporgın Dijital Tek.", area: 10, rate: 9500, manager: "Ali Yetkin Şekeroğlu", phone: "(530) 955-32-31", email: "support@exporgin.shop", floor: "Zemin" },
    { name: "Pars Ar Ge Bilgi Tekn.", area: 4, rate: 6934, manager: "Sarp Ertürk", phone: "0 532 704 34 12", email: "sarp@parsarge.com", floor: "Zemin" },
    { name: "Data24k Yazılım Donanım", area: 1, rate: 6934, manager: "Uğur Yılmaz", phone: "+90.533.364 9271", email: "bilgi@data24k.com", floor: "Zemin" },
    { name: "Bayos Teknoloji A.Ş.", area: 1, rate: 9500, manager: "Aytaç Solak", phone: "(530) 280-21-63", email: "info@bayos.com.tr", floor: "Zemin" },
    { name: "Mez Bilişim A.Ş.", area: 1, rate: 7925, manager: "Mehmed Bilgiç", phone: "+90 530 122 36 01", email: "info@mezbilisim.com", floor: "Zemin" },
    { name: "Aymed Medikal Teknoloji", area: 4, rate: 7925, manager: "Emine Kavas Ay", phone: "(533) 272-35-81", email: "muhasebe@aymed.com", floor: "Zemin" },
    { name: "Datatem Bilişim Teknoloji", area: 5, rate: 7925, manager: "Eyüp Temi̇zel", phone: "(506) 636-63-93", email: "info@datatem.com", floor: "Zemin" },
    { name: "Speksko Bilişim Yazılım", area: 2, rate: 7925, manager: "Mehmet Furkan Atlı", phone: "(532) 620-14-88", email: "furkan.atli@spexco.com", floor: "Zemin" },
    { name: "Defterim Teknoloji A.Ş.", area: 2, rate: 9500, manager: "Elif Nur Sayin", phone: "0 (551) 190-82-81", email: "elifnur99@hotmail.com", floor: "Zemin" },
    { name: "Stemxr Yaz. ve Bilişim", area: 1, rate: 7925, manager: "Neşe Arın Kuter", phone: "(532) 727 49 49", email: "info@ayttechnologies.com", floor: "Zemin" },
    { name: "Nuvo Teknoloji Hizmetleri", area: 3, rate: 7925, manager: "Utku Kır", phone: "(532) 454-54-48", email: "utku@nuvotek.com.tr", floor: "Zemin" },
    { name: "Dora Smart Süreç Otomasyon", area: 3, rate: 6934, manager: "Bariş Korkmaz", phone: "0 532 343 88 78", email: "bkorkmaz@ddo.com.tr", floor: "Zemin" },
    { name: "Obamınd Teknoloji", area: 4, rate: 7925, manager: "Ozan Barış Bayraktar", phone: "(531) 884-48-48", email: "bayraktar.ozanbaris@gmail.com", floor: "Zemin" },
    { name: "Turklink Teknoloji A.Ş.", area: 4, rate: 7925, manager: "Mustafa Sak", phone: "532 565 46 40", email: "info@turk.link", floor: "Zemin" },
    { name: "Digicore Yazılım San.", area: 4, rate: 9500, manager: "Fatih", phone: "(532) 609-88-39", email: "fatih@digicore.com.tr", floor: "Zemin" },
    { name: "Fintiya Teknoloji A.Ş.", area: 4, rate: 9500, manager: "Hasan Laçi̇n", phone: "(532) 290-01-29", email: "info@fintiya.com", floor: "Zemin" },
    { name: "Bixcod Yazılım Dan.", area: 3, rate: 6934, manager: "Ömer Kaya", phone: "5397919397", email: "info@bixcod.com", floor: "Zemin" },
    { name: "İstanbul Medchem Sağlık", area: 1, rate: 9500, manager: "Serdar Durdağı", phone: "-", email: "serdardurdagi@gmail.com", floor: "Zemin" },
    { name: "Bi Dataworks Yazılım", area: 3, rate: 6934, manager: "Osman Aktaş", phone: "(534) 650-89-96", email: "info@bidataworks.com", floor: "Zemin" },
    { name: "Smartgreen Çevre Tek.", area: 1, rate: 9500, manager: "Bekir Berker Türker", phone: "0 (505) 396 28 23", email: "berkerturker@gmail.com", floor: "Zemin" },
    { name: "Predico Yazılım", area: 1, rate: 6934, manager: "Mehmed Eroğlu", phone: "0532 136 03 03", email: "eroglume@gmail.com", floor: "Zemin" },
    { name: "Tshirt Plus Dijital", area: 5, rate: 9500, manager: "İsmail Genç", phone: "-", email: "tshirtplus2020@gmail.com", floor: "Zemin" },
    { name: "Hızırtech Dijital Ürün", area: 1, rate: 9500, manager: "Ali̇ Aksakal", phone: "0546 574727 57", email: "info@tolltake.com", floor: "Zemin" },
    { name: "İnno Kontrol Bilişim", area: 2, rate: 9500, manager: "İsmail Helva", phone: "(542) 440-31-32", email: "info@logsign.net", floor: "Zemin" },
    { name: "Novitopia Bilgi Çözümleri", area: 6, rate: 9500, manager: "Ömer Özdinç", phone: "(532) 772-99-85", email: "bilgi@sd.com.tr", floor: "Zemin" }
];

export const cekmekoyKuluckaData = [
    { name: "Team 24 Plus Yazılım A.Ş.", area: 4, rate: 4458, manager: "Müfit Süer", phone: "-", email: "mufit.suer@team24plus.com", floor: "Zemin" },
    { name: "Arraytex Teknoloji A.Ş.", area: 3, rate: 4458, manager: "Hilal Rabia Hayek", phone: "(534) 460-06-03", email: "hilal.ogut@arraytex.com", floor: "Zemin" },
    { name: "Titrabox Akıllı Analiz Sistemleri...", area: 3, rate: 4458, manager: "Aydın Yuvalı", phone: "(542) 619-56-06", email: "info@titrabox.com", floor: "Zemin" },
    { name: "Datarul Veri Yönetimi A.Ş.", area: 5, rate: 4750, manager: "Handan Altıntaş", phone: "(530) 691-84-98", email: "handan.altintas@smartmind.com.tr", floor: "Zemin" },
    { name: "Finprise Yazılım Teknoloji Ltd.Şti.", area: 1, rate: 4458, manager: "Fatih Ciğeroğlu", phone: "(507) 178-20-81", email: "fcigeroglu@gmail.com", floor: "Zemin" },
    { name: "Global Rf Technology Defense...", area: 2, rate: 4750, manager: "Ümit Yurdaer", phone: "-", email: "umityurdaerr@gmail.com", floor: "Zemin" },
    { name: "Z Hesap Yazılım A.Ş", area: 2, rate: 4750, manager: "-", phone: "-", email: "-", floor: "Zemin" },
    { name: "Tarosis Tarımsal Robotik Sistemler...", area: 1, rate: 4750, manager: "-", phone: "-", email: "-", floor: "Zemin" },
    { name: "Midar Yazılım A.Ş.", area: 5, rate: 4750, manager: "Ümit Çınar", phone: "-", email: "midaryazilim@gmail.com", floor: "Zemin" },
    { name: "Obelisk Teknoloji", area: 1, rate: 4750, manager: "Kemal Baykal", phone: "-", email: "kemal.baykal@gmail.com", floor: "Zemin" },
    { name: "Enkare Yazılım ve Mühendislik A.Ş", area: 2, rate: 4750, manager: "Enes Engin", phone: "(545) 367-36-37", email: "enesengin@en-kare.com", floor: "Zemin" },
    { name: "Veriden Bilgi Teknolojileri...", area: 5, rate: 4458, manager: "Gökalp Erbeyoğlu", phone: "(506) 720-87-32", email: "gokalp@veriden.ai", floor: "Zemin" },
    { name: "Aweb Yazılım Ticaret Anonim Şirketi", area: 2, rate: 4458, manager: "Hamdi Ekmen", phone: "+90 (216) 499 1 666", email: "he@aweb.com.tr", floor: "Zemin" }
];

export const cekmekoyData = [
    { name: "YÖNETİM", floor: "5", area: 1462, rate: 0, manager: "", phone: "", email: "" },
    { name: "Arma Digital Medya A.Ş.", floor: "5", area: 63, rate: 1724, manager: "Yücel Atasoy", phone: "(533) 361-82-57", email: "medya@armadigital.com.tr" },
    { name: "Sofart Teknoloji Ltd. Şti.", floor: "5", area: 28, rate: 1750, manager: "Görkem Aşık", phone: "(552) 212-44-94", email: "gorkem.asik85@gmail.com" },
    { name: "Alarko Dijital Teknoloji A.Ş.", floor: "5", area: 137, rate: 1623, manager: "Serkan Demir", phone: "0532-570-60-18", email: "serkan.demir@alarko.com.tr" },
    { name: "Dijital Veri Yönetimi Ltd.", floor: "4", area: 39, rate: 1034, manager: "Murat Nurullahoğlu", phone: "(531) 668-11-03", email: "murat.nurullahoglu@beinsights.net" },
    { name: "Octoxlabs Yazılım A.Ş.", floor: "4", area: 111, rate: 1500, manager: "İsmail Velioğlu", phone: "0542 387 66 10", email: "ismail.velioglu@octoxlabs.com" },
    { name: "Proday Teknoloji Ltd. Şti.", floor: "4", area: 111, rate: 1545, manager: "Hakan Ay", phone: "0536 517 52 13", email: "hakan.ay@prodaytech.com.tr" },
    { name: "Intellium Bilişim A.Ş.", floor: "4", area: 100, rate: 1034, manager: "Turgut Özçelikyürek", phone: "(532) 682 75 83", email: "turgut.ozcelikyurek@intellium.com.tr" },
    { name: "İnnotim Yazılım Ltd. Şti.", floor: "4", area: 110, rate: 1176, manager: "İsmail Helva", phone: "(542) 440-31-32", email: "ismail@logsign.net" },
    { name: "Bti Bilişim Yazılım Dan. Ltd. Şti.", floor: "4", area: 98, rate: 1034, manager: "Mete Ersoy Tufan", phone: "(532) 374-02-69", email: "mete.tufan@btidanismanlik.com" },
    { name: "Customstech Bilgi Tek. A.Ş.", floor: "4", area: 98, rate: 1724, manager: "Oğuz Çekin", phone: "(539) 380-31-28", email: "oguzcekin@gmail.com" },
    { name: "Octoxlabs Yazılım A.Ş.", floor: "4", area: 98, rate: 1500, manager: "İsmail Velioğlu", phone: "0542 387 66 10", email: "ismail.velioglu@octoxlabs.com" },
    { name: "Logo Makine Otomasyon Ltd.", floor: "4", area: 84.5, rate: 1724, manager: "Arif Gelen", phone: "(533) 241-04-75", email: "arif.gelen@argerobotik.com" },
    { name: "Rsu Bilişim A.Ş.", floor: "4", area: 39, rate: 1034, manager: "Kaan İlter", phone: "(554) 285-86-35", email: "kaan.ilter@rsu.com.tr" },
    { name: "Sipay Elektronik Para A.Ş.", floor: "4", area: 91, rate: 1460, manager: "Semih Muşabak", phone: "0555 233 00 46", email: "semih.musabak@sipay.com.tr" },
    { name: "Ayt Teknoloji A.Ş.", floor: "4", area: 98, rate: 1034, manager: "Neşe Arın Kuter", phone: "(532) 727 49 49", email: "nese.arin@ayttechnologies.com" },
    { name: "Commitup Teknoloji Hiz. A.Ş.", floor: "4", area: 111, rate: 1176, manager: "Derya Tekinşen", phone: "(532) 582-78-19", email: "derya.tekinsen@payporter.com.tr" },
    { name: "Öneriver Yazılım A.Ş.", floor: "4", area: 39, rate: 1034, manager: "Y. Nejat Özek", phone: "0532 295 78 80", email: "nozek@infina.com.tr" },
    { name: "Kodit Teknoloji Ltd. Şti.", floor: "4", area: 98, rate: 1176, manager: "Gürkan Özcan", phone: "538 911 48 36", email: "gurkan.ozcan@kodit.com.tr" },
    { name: "Bti Bilişim Yazılım Dan. Ltd. Şti.", floor: "4", area: 39, rate: 1034, manager: "Mete Ersoy Tufan", phone: "(532) 374-02-69", email: "mete.tufan@btidanismanlik.com" },
    { name: "Hatko Innovative Sol. Ltd.", floor: "3", area: 39, rate: 1176, manager: "Gupse Kobaş", phone: "(530) 677-81-32", email: "gupsekobas@hatkotek.com" },
    { name: "Bti Bilişim Yazılım Dan. Ltd. Şti.", floor: "3", area: 98, rate: 1034, manager: "Mete Ersoy Tufan", phone: "(532) 374-02-69", email: "mete.tufan@btidanismanlik.com" },
    { name: "Bti Bilişim Yazılım Dan. Ltd. Şti.", floor: "3", area: 39, rate: 1034, manager: "Mete Ersoy Tufan", phone: "(532) 374-02-69", email: "mete.tufan@btidanismanlik.com" },
    { name: "Enpos Bilişim San. A.Ş.", floor: "3", area: 85, rate: 1176, manager: "Enver Polat", phone: "532 427 02 00", email: "finans@enpos.com.tr" },
    { name: "Jforce Bilişim Teknolojileri A.Ş.", floor: "3", area: 117, rate: 1034, manager: "Arzu Devrim", phone: "(539) 372 15 01", email: "arzu.devrim@jforce.com" },
    { name: "Machinarium Teknoloji A.Ş.", floor: "3", area: 117, rate: 1176, manager: "Gökhan Uygun", phone: "0 506 854 20 21", email: "gokhan@machinarium.co" },
    { name: "Topraq Tarım Tek. A.Ş.", floor: "3", area: 117, rate: 1176, manager: "Fırat Kerim Ersoy", phone: "-", email: "firat.ersoy@topraq.ai" },
    { name: "Axiro Semiconductor A.Ş.", floor: "3", area: 117, rate: 1750, manager: "Başar Özyılmaz", phone: "(532) 694-32-80", email: "basar.ozyilmaz@axiro.com" },
    { name: "Neno Teknoloji Ltd. Şti.", floor: "3", area: 84, rate: 1034, manager: "Serdar Gökçe", phone: "(505) 616-28-57", email: "serdar.gokce@nenoteknoloji.com" },
    { name: "Depixen Yazılım A.Ş.", floor: "3", area: 98, rate: 1460, manager: "Özgül Atay", phone: "0530 746 98 93", email: "ozgul.atay@depixen.com" },
    { name: "Nat Yazılım A.Ş.", floor: "3", area: 39, rate: 1176, manager: "Onur Aytaç", phone: "532 603 30 43", email: "onur.aytac@natyazilim.com.tr" },
    { name: "Topraq Tarım Tek. A.Ş.", floor: "3", area: 90, rate: 1176, manager: "Fırat Kerim Ersoy", phone: "-", email: "firat.ersoy@topraq.ai" },
    { name: "Topraq Tarım Tek. A.Ş.", floor: "3", area: 98, rate: 1176, manager: "Fırat Kerim Ersoy", phone: "-", email: "firat.ersoy@topraq.ai" },
    { name: "Valtek Yapı Tek. Ltd. Şti.", floor: "3", area: 39, rate: 1034, manager: "Tamer Sevinç", phone: "0532 557 35 55", email: "tsevinc@valtek.com.tr" },
    { name: "Aktiftech Teknoloji A.Ş.", floor: "2", area: 1690, rate: 694, manager: "Özgür Bilgin", phone: "0530-954-76-11", email: "ozgur.bilgin@aktifbank.com.tr" },
    { name: "Ainos Bilgi Teknolojileri A.Ş.", floor: "1", area: 515, rate: 0, manager: "Erdal Yaman", phone: "0 531 8514975", email: "erdalyaman@ainos.com.tr" },
    { name: "Martaş Digital Teknoloji Hiz. A.Ş.", floor: "1", area: 285, rate: 1377, manager: "Ziya Özalp", phone: "0532 426 08 22", email: "nihat.cabadak@martasdijital.com.tr" },
    { name: "Optimus Yazılım Ltd. Şti.", floor: "1", area: 190, rate: 1750, manager: "Ferhat Alkan", phone: "0(542)251 4716", email: "ferhat.alkan@optimusyazilim.com.tr" }
];
